spring:
  application:
    name: catams
  profiles:
    group:
      demo: e2e-local
  
  # Default database configuration (connects to Docker PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5433/catams
    username: catams_user
    password: catams_password
    driver-class-name: org.postgresql.Driver
  
  # Default JPA configuration (can be overridden by profiles)
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Default Flyway configuration (enabled by default, disabled in test profiles)
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  
  # Security configuration
  security:
    jwt:
      secret: ${JWT_SECRET:PDUWUYQxl+aNU04furgt8QkbtSYun0wJSP3/5bMSo6I=}
      expiration: ${JWT_EXPIRATION:86400000}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Timesheet business rules configuration (shared default)
timesheet:
  hours:
    max: 38.0

app:
  cors:
    allowed-origins: "http://localhost:5173"

# Default server configuration
server:
  port: 8080
