# Development Profile Configuration
# Inherits defaults from application.yml, overrides specific dev settings

spring:
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/catams
    username: catams_user
    password: catams_password
    driver-class-name: org.postgresql.Driver

  # JPA Configuration (dev-specific overrides)
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Security Configuration
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 28800000

# Logging Configuration
logging:
  level:
    com.usyd.catams: DEBUG
    org.springframework.security: DEBUG

