spring:
  application:
    name: catams

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Timesheet business rules configuration (shared default)
timesheet:
  hours:
    max: 38.0