# Demo Profile Configuration (no Docker required)

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

app:
  cors:
    allowed-origins: "http://localhost:5174"

server:
  port: 8084
  servlet:
    context-path: ""

logging:
  level:
    com.usyd.catams: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"


