# Main Test Profile (fallback for tests)
# Note: Specific test profiles (test, integration-test) should be used instead

spring:
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    
  # Disable Flyway for tests
  flyway:
    enabled: false
    
  # Security Configuration
  security:
    jwt:
      secret: ${JWT_SECRET:test-secret}
      expiration: 3600000 # 1 hour for tests

# Server Configuration
server:
  servlet:
    context-path: 

# Logging Configuration
logging:
  level:
    com.usyd.catams: DEBUG
    org.springframework.security: DEBUG