-- Lecturer to Course assignments for scoping dashboards and approval queues

CREATE TABLE IF NOT EXISTS lecturer_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lecturer_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    CONSTRAINT fk_lecturer_assignments_lecturer FOREIGN KEY (lecturer_id) REFERENCES users(id),
    CONSTRAINT fk_lecturer_assignments_course FOREIGN KEY (course_id) REFERENCES courses(id),
    CONSTRAINT ux_lecturer_assignments_lecturer_course UNIQUE (lecturer_id, course_id)
);

CREATE INDEX IF NOT EXISTS idx_lecturer_assignment_lecturer ON lecturer_assignments(lecturer_id);
CREATE INDEX IF NOT EXISTS idx_lecturer_assignment_course ON lecturer_assignments(course_id);

-- Backfill assignments from existing courses to preserve behavior
INSERT INTO lecturer_assignments (lecturer_id, course_id)
SELECT c.lecturer_id, c.id FROM courses c
ON CONFLICT (lecturer_id, course_id) DO NOTHING;
